### ISSUE TITLE
ValueError: mismatch: got 20 values to set 18 parameters

### ISSUE THREAD

**Issue by wangxiao5791509** [imatge-upc/saliency-salgan-2017#13]
**Hi, thanks for the code and trained model. But, I found when load the trained model of discriminator you provided, it shown me the following error. Could you check that model again ? Thanks.** 

Traceback (most recent call last):
  File "wangxiao-02-train.py", line 184, in <module>
    train()     
  File "wangxiao-02-train.py", line 169, in train
    load_weights(net=model.discriminator['fc5'], path="test/discrim_", epochtoload=90)
  File "/media/wangxiao/724eaeef-e688-4b09-9cc9-dfaca44079b2/saliency-salgan-2017-master-tracking/scripts/utils.py", line 24, in load_weights
    lasagne.layers.set_all_param_values(net, param_values)
  File "/home/wangxiao/Lasagne/src/lasagne/lasagne/layers/helper.py", line 512, in set_all_param_values
    (len(values), len(params)))
ValueError: mismatch: got 20 values to set 18 parameters

**Comment by junting** [comment]
Hi @wangxiao5791509 ,

Sorry, the key for the discriminator was wrong, please try this:
`load_weights(net=model.discriminator['prob'], path="test/discrim_", epochtoload=90)`

**Comment by wangxiao5791509** [comment]
@junting Thanks your kind replay. But still get wrong, the same problem: mismatched. Does it caused by input image size ? I keep it the same as yours, but still can not run smoothly ... 

Traceback (most recent call last):
  File "wangxiao-02-train.py", line 187, in <module>
    train()     
  File "wangxiao-02-train.py", line 169, in train
    load_weights(net=model.discriminator['prob'], path="./discrim_", epochtoload=90)
  File "/media/wangxiao/724eaeef-e688-4b09-9cc9-dfaca44079b2/saliency-salgan-2017-master-tracking/scripts/utils.py", line 24, in load_weights
    lasagne.layers.set_all_param_values(net, param_values)
  File "/home/wangxiao/Lasagne/src/lasagne/lasagne/layers/helper.py", line 518, in set_all_param_values
    (p.get_value().shape, v.shape))
**ValueError: mismatch: parameter has shape (12288, 100) but value to set has shape (12288, 60)**

**Comment by remega** [comment]
Hi, guys. I met the same problem. Have you solved it? Looking forward to your reply!

**Comment by remega** [comment]
I mean, ValueError: mismatch: parameter has shape (12288, 100) but value to set has shape (12288, 60)

**Comment by Saloqin** [comment]
+1
ValueError: mismatch: parameter has shape (12288, 100) but value to set has shape (12288, 60)
anyone knows whats going on?
