### ISSUE TITLE
ImportError: requires GPU support   Is that anyone could help me ? thanks

### ISSUE THREAD

**Issue by chenbolinstudent** [imatge-upc/saliency-salgan-2017#39]
Traceback (most recent call last):
  File "/home/bl/PycharmProjects/saliency-salgan-2017-master/scripts/02-train.py", line 17, in <module>
    from models.model_salgan import ModelSALGAN
  File "/home/bl/PycharmProjects/saliency-salgan-2017-master/scripts/models/model_salgan.py", line 8, in <module>
    import discriminator
  File "/home/bl/PycharmProjects/saliency-salgan-2017-master/scripts/models/discriminator.py", line 6, in <module>
    import nn
  File "/home/bl/PycharmProjects/saliency-salgan-2017-master/scripts/models/nn.py", line 9, in <module>
    from lasagne.layers import dnn
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/dnn.py", line 42, in <module>
    "requires GPU support -- see http://lasagne.readthedocs.org/en/"
ImportError: requires GPU support -- see http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support

Is that anyone could help me ? thanks

**Comment by mmppllhaha** [comment]
you need a GPU

**Comment by KongHangd** [comment]
请问你的问题解决了吗，我也遇到了同样的问题
